name: C/C++ CI

on:
  push:
    branches:
    - 3.3.5

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test
